-- testing values --
--INSERT INTO actors (name) VALUES ('Samwise');
--INSERT INTO actors (name) VALUES ('Sarah');
--
--INSERT INTO categories (name) VALUES ('Food');
--INSERT INTO categories (name) VALUES ('Clothes');
--
--INSERT INTO expenses (date, value, is_regular, category_id) VALUES ('2023-06-05', 100, true, 1);
--INSERT INTO expenses (date, value, is_regular, category_id) VALUES ('2023-06-06', 10, true, 2);
--INSERT INTO expenses (date, value, is_regular, category_id) VALUES ('2023-06-12', 100, true, 1);
--INSERT INTO expenses (date, value, is_regular, category_id) VALUES ('2023-06-13', 10, true, 2);
--INSERT INTO expenses (date, value, is_regular, category_id) VALUES ('2023-06-17', 100, true, 1);
--INSERT INTO expenses (date, value, is_regular, category_id) VALUES ('2023-06-18', 10, true, 2);
--INSERT INTO expenses (date, value, is_regular, category_id) VALUES ('2023-06-25', 100, true, 1);
--INSERT INTO expenses (date, value, is_regular, category_id) VALUES ('2023-06-26', 10, true, 2);
--
--INSERT INTO income_sources (name, value, currency, accrual_day) VALUES ('John salary', 1200, 'USD', 15);
--INSERT INTO income_sources (name, value, currency, accrual_day) VALUES ('Samwise influencer royalties', 4000, 'UAH', 31);